CREATE TABLE customers (
    customer_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    full_name      VARCHAR2(200) NOT NULL,
    email          VARCHAR2(320),
    phone          VARCHAR2(40),
    CONSTRAINT customers_pk PRIMARY KEY (customer_id)
);

CREATE TABLE vehicles (
    vehicle_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customer_id    NUMBER NOT NULL,
    vin            VARCHAR2(17) NOT NULL,
    make           VARCHAR2(100),
    model          VARCHAR2(100),
    model_year     NUMBER(4),
    CONSTRAINT vehicles_pk PRIMARY KEY (vehicle_id),
    CONSTRAINT vehicles_customer_fk FOREIGN KEY (customer_id)
        REFERENCES customers (customer_id),
    CONSTRAINT vehicles_vin_uk UNIQUE (vin)
);

CREATE TABLE service_appointments (
    appointment_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customer_id             NUMBER NOT NULL,
    vehicle_id              NUMBER NOT NULL,
    received_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at            TIMESTAMP WITH TIME ZONE,
    odometer_miles          NUMBER(10),
    service_summary         CLOB,
    warranty_type           VARCHAR2(30) DEFAULT 'NONE' NOT NULL,
    total_cost              NUMBER(12,2) DEFAULT 0 NOT NULL,
    warranty_covered_amount NUMBER(12,2) DEFAULT 0 NOT NULL,
    customer_paid_amount    NUMBER(12,2) DEFAULT 0 NOT NULL,
    CONSTRAINT service_appointments_pk PRIMARY KEY (appointment_id),
    CONSTRAINT service_appt_customer_fk FOREIGN KEY (customer_id)
        REFERENCES customers (customer_id),
    CONSTRAINT service_appt_vehicle_fk FOREIGN KEY (vehicle_id)
        REFERENCES vehicles (vehicle_id),
    CONSTRAINT service_appt_warranty_ck CHECK (
        warranty_type IN ('NONE', 'MANUFACTURER', 'EXTENDED', 'RECALL')
    ),
    CONSTRAINT service_appt_amounts_ck CHECK (
        total_cost >= 0
        AND warranty_covered_amount >= 0
        AND customer_paid_amount >= 0
    )
);

CREATE TABLE service_items (
    service_item_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    appointment_id   NUMBER NOT NULL,
    description      VARCHAR2(1000) NOT NULL,
    labor_cost       NUMBER(12,2) DEFAULT 0 NOT NULL,
    parts_cost       NUMBER(12,2) DEFAULT 0 NOT NULL,
    CONSTRAINT service_items_pk PRIMARY KEY (service_item_id),
    CONSTRAINT service_items_appt_fk FOREIGN KEY (appointment_id)
        REFERENCES service_appointments (appointment_id)
        ON DELETE CASCADE,
    CONSTRAINT service_items_amounts_ck CHECK (
        labor_cost >= 0
        AND parts_cost >= 0
    )
);

CREATE INDEX vehicles_customer_ix
    ON vehicles (customer_id);

CREATE INDEX service_appt_vehicle_ix
    ON service_appointments (vehicle_id);

CREATE INDEX service_items_appt_ix
    ON service_items (appointment_id);

INSERT ALL
  INTO customers (customer_id, full_name, email, phone) VALUES (1, 'Ava Johnson', 'ava.johnson@example.com', '555-0101')
  INTO customers (customer_id, full_name, email, phone) VALUES (2, 'Ben Carter', 'ben.carter@example.com', '555-0102')
  INTO customers (customer_id, full_name, email, phone) VALUES (3, 'Chloe Nguyen', 'chloe.nguyen@example.com', '555-0103')
  INTO customers (customer_id, full_name, email, phone) VALUES (4, 'Diego Martinez', 'diego.martinez@example.com', '555-0104')
  INTO customers (customer_id, full_name, email, phone) VALUES (5, 'Emma Wilson', 'emma.wilson@example.com', '555-0105')
  INTO customers (customer_id, full_name, email, phone) VALUES (6, 'Farah Khan', 'farah.khan@example.com', '555-0106')
  INTO customers (customer_id, full_name, email, phone) VALUES (7, 'Grace Lee', 'grace.lee@example.com', '555-0107')
  INTO customers (customer_id, full_name, email, phone) VALUES (8, 'Henry Brooks', 'henry.brooks@example.com', '555-0108')
  INTO customers (customer_id, full_name, email, phone) VALUES (9, 'Isabella Rossi', 'isabella.rossi@example.com', '555-0109')
  INTO customers (customer_id, full_name, email, phone) VALUES (10, 'Jamal Turner', 'jamal.turner@example.com', '555-0110')
SELECT 1 FROM dual;

INSERT ALL
  INTO vehicles (vehicle_id, customer_id, vin, make, model, model_year) VALUES (1, 1, '1HGCM82633A004352', 'Example Motors', '47C', 2025)
  INTO vehicles (vehicle_id, customer_id, vin, make, model, model_year) VALUES (2, 2, '2T1BURHE5JC034567', 'Example Motors', '24A', 2025)
  INTO vehicles (vehicle_id, customer_id, vin, make, model, model_year) VALUES (3, 3, '5NPE24AF8GH123456', 'Example Motors', '47C', 2024)
  INTO vehicles (vehicle_id, customer_id, vin, make, model, model_year) VALUES (4, 4, '1FMCU0GXXFUA12345', 'Example Motors', '24A', 2026)
  INTO vehicles (vehicle_id, customer_id, vin, make, model, model_year) VALUES (5, 5, 'JN1AZ4EH3DM382001', 'Example Motors', '58D', 2026)
  INTO vehicles (vehicle_id, customer_id, vin, make, model, model_year) VALUES (6, 6, 'WBA8E9G58JNU12345', 'Example Motors', '330i', 2024)
  INTO vehicles (vehicle_id, customer_id, vin, make, model, model_year) VALUES (7, 7, 'KM8K12AA7KU234567', 'Example Motors', '31B', 2026)
  INTO vehicles (vehicle_id, customer_id, vin, make, model, model_year) VALUES (8, 8, '3VW2B7AJ5HM345678', 'Example Motors', '47C', 2025)
  INTO vehicles (vehicle_id, customer_id, vin, make, model, model_year) VALUES (9, 9, '1C4RJFBG9KC456789', 'Example Motors', '31B Cherokee', 2026)
  INTO vehicles (vehicle_id, customer_id, vin, make, model, model_year) VALUES (10, 10, 'YV4A22PK5H1123456', 'Example Motors', '24A', 2025)
SELECT 1 FROM dual;

INSERT INTO service_appointments (
    appointment_id,
    customer_id,
    vehicle_id,
    received_at,
    completed_at,
    odometer_miles,
    service_summary,
    warranty_type,
    total_cost,
    warranty_covered_amount,
    customer_paid_amount
)
SELECT
    appointment_id,
    customer_id,
    vehicle_id,
    received_at,
    completed_at,
    odometer_miles,
    service_summary,
    warranty_type,
    total_cost,
    warranty_covered_amount,
    total_cost - warranty_covered_amount
FROM (
    SELECT
        LEVEL AS appointment_id,
        MOD(LEVEL - 1, 10) + 1 AS customer_id,
        MOD(LEVEL - 1, 10) + 1 AS vehicle_id,
        FROM_TZ(TIMESTAMP '2025-01-06 08:00:00', '-08:00') + NUMTODSINTERVAL(LEVEL * 9, 'DAY') AS received_at,
        FROM_TZ(TIMESTAMP '2025-01-06 16:30:00', '-08:00') + NUMTODSINTERVAL(LEVEL * 9, 'DAY') AS completed_at,
        18000 + (LEVEL * 1375) AS odometer_miles,
        CASE MOD(LEVEL, 6)
            WHEN 0 THEN 'Oil change, tire rotation, and multi-point inspection'
            WHEN 1 THEN 'Brake inspection and brake component replacement'
            WHEN 2 THEN 'Engine diagnostic and sensor replacement'
            WHEN 3 THEN 'Battery, charging system, and electrical inspection'
            WHEN 4 THEN 'Recall service and software update'
            ELSE 'Scheduled maintenance and fluid service'
        END AS service_summary,
        CASE
            WHEN MOD(LEVEL, 10) IN (3, 7) THEN 'MANUFACTURER'
            WHEN MOD(LEVEL, 10) IN (4, 8) THEN 'EXTENDED'
            WHEN MOD(LEVEL, 10) = 5 THEN 'RECALL'
            ELSE 'NONE'
        END AS warranty_type,
        150 + (MOD(LEVEL, 8) * 75) AS total_cost,
        CASE
            WHEN MOD(LEVEL, 10) IN (3, 5, 7) THEN 150 + (MOD(LEVEL, 8) * 75)
            WHEN MOD(LEVEL, 10) IN (4, 8) THEN ROUND((150 + (MOD(LEVEL, 8) * 75)) * 0.70, 2)
            ELSE 0
        END AS warranty_covered_amount
    FROM dual
    CONNECT BY LEVEL <= 30
);

INSERT INTO service_items (
    service_item_id,
    appointment_id,
    description,
    labor_cost,
    parts_cost
)
SELECT
    LEVEL AS service_item_id,
    MOD(LEVEL - 1, 30) + 1 AS appointment_id,
    CASE MOD(LEVEL, 10)
        WHEN 0 THEN 'Oil and filter replacement'
        WHEN 1 THEN 'Tire rotation'
        WHEN 2 THEN 'Multi-point inspection'
        WHEN 3 THEN 'Brake pad replacement'
        WHEN 4 THEN 'Diagnostic scan'
        WHEN 5 THEN 'Battery test and replacement'
        WHEN 6 THEN 'Software update'
        WHEN 7 THEN 'Fluid exchange'
        WHEN 8 THEN 'Air filter replacement'
        ELSE 'Road test and quality check'
    END AS description,
    25 + (MOD(LEVEL, 6) * 20) AS labor_cost,
    CASE MOD(LEVEL, 10)
        WHEN 0 THEN 38
        WHEN 3 THEN 110
        WHEN 5 THEN 165
        WHEN 7 THEN 48
        WHEN 8 THEN 28
        ELSE 0
    END AS parts_cost
FROM dual
CONNECT BY LEVEL <= 100;

COMMIT;
